# Generated by Django 5.1.1 on 2024-09-19 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('biography', models.TextField(blank=True)),
                ('art_type', models.CharField(blank=True, choices=[('knitting', 'Knitting'), ('crochet', 'Crochet'), ('embroidery', 'Embroidery'), ('weaving', 'Weaving'), ('dyeing', 'Dyeing'), ('other', 'Other')], max_length=20)),
                ('image', models.URLField(blank=True, max_length=1024, null=True)),
                ('last_visited_notifications', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='profiles.profile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='profiles.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('followed_profile', 'follower'), name='unique_follower')],
            },
        ),
    ]
