# Generated by Django 5.1.1 on 2024-09-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='art_type',
        ),
    ]
