# Generated by Django 5.1.1 on 2024-09-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_art_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(default='https://picsum.photos/id/400/200', max_length=1024),
        ),
    ]
