# Generated by Django 5.1.1 on 2024-09-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='art_type',
            field=models.CharField(blank=True, choices=[('knitting', 'Knitting'), ('crochet', 'Crochet'), ('embroidery', 'Embroidery'), ('weaving', 'Weaving'), ('dyeing', 'Dyeing'), ('other', 'Other')], max_length=20),
        ),
    ]
