# Generated by Django 5.1.1 on 2024-09-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
