# Generated by Django 5.1.1 on 2024-09-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0001_initial'),
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='piece',
            name='image',
            field=models.URLField(default='https://picsum.photos/id/1/800/600', max_length=1024),
        ),
        migrations.AlterField(
            model_name='piece',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='profiles.profile'),
        ),
    ]
