# Generated by Django 5.1.1 on 2024-09-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0002_piece_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
